"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with and , the first terms will be:

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""
seq = [1, 2]

for i in 1:50
    push!(seq, seq[i] + seq[i+1])
    if seq[end] > 4_000_000
        pop!(seq)
        break
    end
end
print(seq)
print("\n")
println(sum([x for x in seq if x % 2 == 0 && x < 4_000_000]))